logLevel: info

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level debug
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        Trace_Error On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*gazoz-app*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/ingress-nginx-controller*.log
        multiline.parser docker, cri
        Tag kube.ingress.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Path /var/log/containers/mongodb*.log
        multiline.parser docker, cri
        Tag kube.mongodb.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        Buffer_Size False
        K8S-Logging.Parser On

    [FILTER]
        Name parser
        Match kube.ingress.*
        Key_Name log
        Parser nginx
        Reserve_Data On

    [FILTER]
        Name parser
        Match kube.mongodb.*
        Key_Name log
        Parser mongodb
        Reserve_Data On

  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Index fluent-bit
        Type _doc
        Host elasticsearch-master
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix logstash
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match kube.ingress.*
        Index fluent-bit
        Type _doc
        Host elasticsearch-master
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix nginx-ingress
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match kube.mongodb.*
        Index fluent-bit
        Type _doc
        Host elasticsearch-master
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix mongodb
        Retry_Limit False
        Suppress_Type_Name On

    [OUTPUT]
        Name es
        Match host.*
        Index fluent-bit
        Type _doc
        Host elasticsearch-master
        Port 9200
        HTTP_User elastic
        HTTP_Passwd 9sRLSqZOhtUpSpyn
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On

  customParsers: |
    [PARSER]
        Name nginx
        Format regex
        Regex ^(?<remote>[^ ]*) - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<host>[^ ]*) (?<server_protocol>[^ ]*)
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name mongodb
        Format regex
        Regex ^(?<time>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.\\d+(?:Z|[+-]\\d{2}:?\\d{2}))\\s+(?<severity>\\w)\\s+(?<component>[^\\s]+)\\s+\\[(?<context>[^\\]]+)\\]\\s+(?<message>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
