apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://helm.elastic.co"
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
          - $values/infra-apps/values/elasticsearch-values.yaml
    - repoURL: "git@gitlab.com:dogdrinker-group/gazozmanagergitops.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
